filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/logs/nginx/access.log
  fields:
    log_type: nginx-access

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
  
output.logstash:
  hosts: ["logstash:5044"]